### ISSUE TITLE
Bug when re-setting parameters

### ISSUE THREAD

**Issue by georgestod** [hichamjanati/mutar#10]
Hi, it seems there is a problem when using 'set_params' on GroupLasso?

The code below should reproduce the error: **some_coeffs** is different from **some_other_coeffs**. I would think **some_other_coeffs** contains the right answer: when alpha is large they should be zero? Apparently, there is an issue with the 'specific coeffs' becoming non zero at some point? Am I right? These ones should always be zero?

`from mutar import GroupLasso
import numpy as np
X = np.array([[[3, 1], [1, 0], [1, 0]],[[0, 2], [2, 3], [2, 3]]], dtype=float)
y = X.sum(axis=2) + 2
glr = GroupLasso().fit(X, y)
glr.fit(X, y).coef_
some_coeffs = glr.set_params(alpha=1e4).fit(X, y).coef_

glr2 = GroupLasso(alpha=1e4)
some_other_coeffs = glr2.fit(X, y).coef_
`

**Comment by hichamjanati** [comment]
Nice catch. yep that's a bug, GroupLasso inherits other parameters from a mother class which should be updated whenever alpha is. I'll fix it asap.
 In the meantime, create a new gl instance when changing alpha.
