### ISSUE TITLE
warm start for the group lasso

### ISSUE THREAD

**Issue by georgestod** [hichamjanati/mutar#8]
Great work, I have been using quite a lot and like it a lot! However, I have an error when using the warm start for the Group Lasso:
from mutar import GroupLasso
import numpy as np
X = np.array([[[3, 1], [1, 0], [1, 0]],[[0, 2], [2, 3], [2, 3]]], dtype=float)
y = X.sum(axis=2) + 2
grouplasso = GroupLasso(warm_start=True).fit(X, y)
grouplasso.fit(X, y).coef_

UnboundLocalError: local variable 'coef_shared_' referenced before assignment

By any chance do you have a quick workaround?

**Comment by hichamjanati** [comment]
Thanks for pointing this out, I fixed the bug. You need to update mutar with the current dev version

```
git clone https://github.com/hichamjanati/mutar
cd mutar
pip install -e .
```

**Comment by georgestod** [comment]
lightening fast, thanks a lot !
